knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page                # Nom du paramètre GET pour la pagination
        sort_field_name: sort          # Nom du paramètre GET pour le tri
        sort_direction_name: direction # Nom du paramètre GET pour la direction de tri
        distinct: true                 # Active la clause DISTINCT dans le COUNT des résultats
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig' # Template par défaut pour la pagination
