#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_chatbot:
    path: /chatbot
    controller: App\Controller\ChatbotController::chatbot
api_calendar:
    path: /api/calendar
    controller: App\Controller\CalendarController::calendarApi