# services.yaml

services:
  # Configuration par défaut pour les services de ce fichier
  _defaults:
    autowire: true # Injecte automatiquement les dépendances dans vos services.
    autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, abonnés d'événements, etc.

  # Rend les classes du répertoire src/ disponibles pour être utilisées en tant que services
  # Cela crée un service par classe dont l'ID est le nom de la classe entièrement qualifié
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Ajoutez d'autres définitions de services lorsque la configuration explicite est nécessaire
  # Veuillez noter que les dernières définitions remplacent toujours les précédentes
  App\Entity\Livraison:
    class: App\Entity\Livraison
    # Vous pouvez ajouter d'autres options de configuration pour votre service d'entité si nécessaire

  App\Controller\LivraisonController:
    autowire: true
    # Définit explicitement l'argument pour le constructeur de la classe
    arguments:
      $livraisonRepository: '@App\Repository\LivraisonRepository'
